spring:
  application:
    name: hackaton-fiapx
    storage: ${STORAGE_TYPE:local}
    upload-location: ${UPLOAD_DIR:uploads}
    output-location: ${OUTPUT_DIR:output}
    executor:
      pool-size: 5
      max-pool-size: 10
      queue-capacity: 25
  cloud:
    aws:
      credentials:
        type: ${AWS_CREDENTIALS_TYPE:session}
        access-key: ${AWS_ACCESS_KEY:access-key}
        secret-key: ${AWS_SECRET_KEY:secret-key}
        session-token: ${AWS_SESSION_TOKEN:session-token}
      region:
        static: ${AWS_REGION:us-east-1}
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:video-processor}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:mysql}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
  liquibase:
    change-log: classpath:db/migration.xml